Map<String, String> moviesTextEn = {
  "now_playing": "Now playing",
  "coming_Soon": "Coming Soon",

  "avengers_infinity": "Avengers: Infinity War",
  "guardians_of_galaxy": "Guardians Of The Galaxy",
  "shang_chi": "Shang chi: Legend of the Ten Rings",
  "batman_superman": "Batman v Superman: Dawn of Justice",

  "shazam_gods": "Shazam! Fury of the Gods",
  "avatar_water": "Avatar 2 : The  Way of Water ",
  "kot_amotax": " Kot Camotax 2",
  "ant_uantumania": "Ant Man Wasp: Quantumania ",

  "time": "2 hours 10 minutes",
  "time1": "2 hours 20 minutes",
  "time2": "3 hours 0 minutes ",
  "time3": "3 hours 30 minutes",

  "rating": "4.0(998)",
  "rating1": "4.0(950)",
  "rating2": "4.0(980)",
  "rating3": "4.0(988)",

  "date": "16.12.2022",
  "date1": "15.01.2023",
  "date2": "20.01.2023",
  "date3": "25.01.2023",
  "action_ci_fi": "Action, Sci-fi",
  "adventure_sci_fi": "Adventure Sci Fi",
};
Map<String, String> moviesTextBn = {
  "now_playing": "এখন চলছে",
  "coming_Soon": "শীঘ্রই আসছে",
  "avengers_infinity": "অ্যাভেঞ্জার্স: ইনফিনিটি ওয়ার",
  "guardians_of_galaxy": "গার্ডিয়ানস অফ দ্য গ্যালাক্সি",
  "shang_chi": "শাং চি: দশটি আংটির কিংবদন্তি",
  "batman_superman": "ব্যাটম্যান বনাম সুপারম্যান: বিচারের দ্বার",
  "shazam_gods": "শাজাম! দেবতাদের ক্রোধ",
  "kot_amotax": "কোট ক্যামোট্যাক্স ২",
  "avatar_water": "অবতার ২: জলের পথ",
  "ant_uantumania": "অ্যান্ট ম্যান ওয়াস্প: কোয়ান্টুম্যানিয়া",
  "time": "২ ঘন্টা ১০ মিনিট",
  "time1": "২ ঘন্টা ২০ মিনিট",
  "time2": "৩ ঘন্টা ০ মিনিট",
  "time3": "৩ ঘন্টা ৩০ মিনিট",
  "rating": "৪.০(৯৯৮)",
  "rating1": "৪.০(৯৫০)",
  "rating2": "৪.০(৯৮০)",
  "rating3": "৪.০(৯৮৮)",
  "date": "১৬.১২.২০২২",
  "date1": "১৫.০১.২০২৩",
  "date2": "২০.০১.২০২৩",
  "date3": "২৫.০১.২০২৩",
  "action_ci_fi": "অ্যাকশন, সায়েন্স ফিকশন",
  "adventure_sci_fi": "অ্যাডভেঞ্চার সায়েন্স ফাই",
};
