// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWiLRd8416MBipGxpvuDVUC1oxFoP17j4',
    appId: '1:1037876935914:web:d5eb66c1d6cd170d316b93',
    messagingSenderId: '1037876935914',
    projectId: 'bloodgroup-d8c5d',
    authDomain: 'bloodgroup-d8c5d.firebaseapp.com',
    storageBucket: 'bloodgroup-d8c5d.appspot.com',
    measurementId: 'G-WEH3K11ZRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhgumGlogYcaruxJ3KoUlnN708HaVbXgU',
    appId: '1:1037876935914:android:ec5366398830296b316b93',
    messagingSenderId: '1037876935914',
    projectId: 'bloodgroup-d8c5d',
    storageBucket: 'bloodgroup-d8c5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADM5Jb1T-kEBOqzJKnt5sLM1FKpHJ-eH4',
    appId: '1:1037876935914:ios:5c42d71f7313e4aa316b93',
    messagingSenderId: '1037876935914',
    projectId: 'bloodgroup-d8c5d',
    storageBucket: 'bloodgroup-d8c5d.appspot.com',
    iosClientId: '1037876935914-jlr91e589svb96ps6dmh30hv3s09214a.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTicketBooging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADM5Jb1T-kEBOqzJKnt5sLM1FKpHJ-eH4',
    appId: '1:1037876935914:ios:5c42d71f7313e4aa316b93',
    messagingSenderId: '1037876935914',
    projectId: 'bloodgroup-d8c5d',
    storageBucket: 'bloodgroup-d8c5d.appspot.com',
    iosClientId: '1037876935914-jlr91e589svb96ps6dmh30hv3s09214a.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTicketBooging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWiLRd8416MBipGxpvuDVUC1oxFoP17j4',
    appId: '1:1037876935914:web:be5fde43f59c3349316b93',
    messagingSenderId: '1037876935914',
    projectId: 'bloodgroup-d8c5d',
    authDomain: 'bloodgroup-d8c5d.firebaseapp.com',
    storageBucket: 'bloodgroup-d8c5d.appspot.com',
    measurementId: 'G-JL50W0XVZR',
  );
}
